version: '3.9'

services:
    php:
        build:
            context: ./docker/php
            args:
                phpunit_version: 9.5.4
                phpstan_version: 0.12.83
                wait_version: 2.8.0
        working_dir: /app
        volumes:
            - '.:/app'
        user: '${UID:-1000}:${GID:-1000}'
        depends_on:
            - postgres
        environment:
            WAIT_HOSTS: postgres:5432
            WAIT_LOGGER_LEVEL: info

    postgres:
        image: postgres:13
        volumes:
            - './docker/pgsql:/docker-entrypoint-initdb.d'
        environment:
            POSTGRES_DB: repositoring
            POSTGRES_USER: bruce
            POSTGRES_PASSWORD: mypass
        command: ["postgres", "-c", "log_statement=all"]
