version: '3.9'

services:
    php:
        build:
            context: ./docker
            args:
                phpunit_version: 9.5.4
        working_dir: /app
        volumes:
            - '.:/app'
        user: '${UID:-1000}:${GID:-1000}'
