version: '3.9'

services:
    php:
        build:
            context: ./docker/php
            args:
                deptrac_version: 0.19.3
                php_cs_fixer_version: v3.6.0
                phpstan_version: 1.4.6
                phpunit_version: 9.5.14
                wait_version: 2.9.0
        working_dir: /app
        volumes:
            - '.:/app'
        user: '${UID:-1000}:${GID:-1000}'
        depends_on:
            - postgres
        environment:
            WAIT_HOSTS: postgres:5432
            WAIT_LOGGER_LEVEL: info

    postgres:
        image: postgres:13
        volumes:
            - './docker/pgsql:/docker-entrypoint-initdb.d'
        environment:
            POSTGRES_DB: repositoring
            POSTGRES_USER: bruce
            POSTGRES_PASSWORD: mypass
        command: ["postgres", "-c", "log_statement=all"]
