version: '3.9'

services:
    php:
        build:
            context: ./docker/php
            args:
                wait_version: 2.12.1 # https://github.com/ufoscout/docker-compose-wait/tags
                phpunit_version: 10.5.8 # https://github.com/sebastianbergmann/phpunit/tags
                phpstan_version: 1.10.56 # https://github.com/phpstan/phpstan/tags
                deptrac_version: 1.0.2 # https://github.com/qossmic/deptrac/tags
                php_cs_fixer_version: v3.47.1 # https://github.com/friendsofphp/php-cs-fixer/tags
                php_security_checker_version: 2.0.6 # https://github.com/fabpot/local-php-security-checker/tags
        working_dir: /app
        volumes:
            - '.:/app'
        user: '${UID:-1000}:${GID:-1000}'
        depends_on:
            - postgres
        environment:
            WAIT_HOSTS: postgres:5432
            WAIT_LOGGER_LEVEL: info

    postgres:
        image: postgres:13
        volumes:
            - './docker/pgsql:/docker-entrypoint-initdb.d'
        environment:
            POSTGRES_DB: repositoring
            POSTGRES_USER: bruce
            POSTGRES_PASSWORD: mypass
        command: ["postgres", "-c", "log_statement=all"]
